1 ver
De-Len/Lab_8-WindowsForms pull request #1
Opened 2024-04-18 18:19 UTC by De-Len

2024-04-19 04:07 UTC, Hamjoshua requested changes

2024-04-19 04:07 UTC, Hamjoshua commented on WindowsFormsApp1/Lab_8-WindowsForms/Model.cs
> +    // "Кичливость философии не совмещается со смирением"
"Ты не можешь ничего сказать, кроме слов"

2024-04-19 04:07 UTC, Hamjoshua commented on WindowsFormsApp1/Lab_8-WindowsForms/Model.cs
> +        public void SynsDirectory(string Path1, string Path2, DirectoryChoice directoryChoice, out List<string> createdFiles, out List<string> deletedFiles, out List<string> replacedFiles)
Опечатка: SyncDirectory

2024-04-19 04:07 UTC, Hamjoshua commented on WindowsFormsApp1/Lab_8-WindowsForms/View.Designer.cs
> +        public string Label3Text
Никогда не лезь в автоматический код дизайнера формы (Designer.cs). Если требуется изменить величину, меняй в коде формы

2024-04-19 04:07 UTC, Hamjoshua commented on WindowsFormsApp1/Lab_8-WindowsForms/IView.cs
> +        string TextBox2Text { get; set; }
Неявные имена переменных: не раскрыта их суть

2024-04-19 04:07 UTC, Hamjoshua commented on WindowsFormsApp1/Lab_8-WindowsForms/Model.cs
> +        static bool FilesAreEqual(string file1, string file2)
Подразумеваются пути. Тогда уж filePath1

2024-04-19 04:07 UTC, Hamjoshua commented on WindowsFormsApp1/Lab_8-WindowsForms/Model.cs
> +        public void SynsDirectory(string Path1, string Path2, DirectoryChoice directoryChoice, out List<string> createdFiles, out List<string> deletedFiles, out List<string> replacedFiles)
Использование Out'ов в void методах негоже. Придумай другой выход, как вернуть объект с тремя списками файлов

2024-04-19 04:07 UTC, Hamjoshua commented on WindowsFormsApp1/Lab_8-WindowsForms/Model.cs
> +                MessageBox.Show("Директории уже синхронизированы", "Ошибка", MessageBoxButtons.OK, MessageBoxIcon.Information);
MessageBox уже из UI касты, а тут ее использует обычный Model'людин. Непорядок. В MVP модель ничего не должна знать об UI касте

2024-04-19 04:07 UTC, Hamjoshua commented on WindowsFormsApp1/Lab_8-WindowsForms/Presenter.cs
> +        private void Sync2(object sender, EventArgs e)
Код Sync2 и Sync1 повторяется. Меняется лишь прибавка к строке: "в первой" или "во второй" директории. Содержание близнецов дорого обходится в коде. Лучше содержать один метод с параметром. А от параметра и будет зависеть, в какой именно папке произошли изменения

2024-04-19 04:07 UTC, Hamjoshua commented on WindowsFormsApp1/Lab_8-WindowsForms/Model.cs
> +                    replacedFiles.Add(fileName);
Слишком перегруженный метод: больше 40 строк. Пусть для каждого списка файлов будет свой метод

2024-04-19 04:07 UTC, Hamjoshua commented on WindowsFormsApp1/Lab_8-WindowsForms/IView.cs
> +        string GetPath2();
Эти методы не нужны, поскольку у тебя уже есть две string переменные для хранения путей папок

2024-04-19 04:07 UTC, Hamjoshua commented on WindowsFormsApp1/Lab_8-WindowsForms/View.cs
> +            return _presenter.GetPath1();
Если написать в путь бяку, то программа вылетит. Напиши обработчик ошибок или воспользуйся FileBrowserDialog

2024-04-19 04:07 UTC, Hamjoshua commented on WindowsFormsApp1/Lab_8-WindowsForms/View.cs
> +            return _presenter.GetPath1();
Во втором случае лучше сделать текстбоксы недоступными для изменения

2024-04-19 04:07 UTC, Hamjoshua commented on WindowsFormsApp1/Lab_8-WindowsForms/Presenter.cs
> +        public string GetPath1()
Эти методы в презнтере тоже не нужны

2024-04-19 04:07 UTC, Hamjoshua commented on WindowsFormsApp1/Lab_8-WindowsForms/View.cs
> +        private void button2_Click(object sender, EventArgs e)
Даже у UI-компонентов должны быть осмысленные названия. Иначе код будет трудно понять. Названия можно изменить в конструкторе формы: Разработка -> Name

2024-04-19 04:35 UTC, De-Len commented on WindowsFormsApp1/Lab_8-WindowsForms/View.Designer.cs
> +        public string Label3Text
Мне это потребовалось для инкапсуляции класса presenter, в котором только вроде бы "Он извлекает данные из хранилища (модели), и форматирует их для отображения в Виде (view)." И я отфарматировал) Если неверно, то могу исправить я прямо в форме делать вывод

2024-04-19 06:50 UTC, De-Len commented on WindowsFormsApp1/Lab_8-WindowsForms/IView.cs
> +        string GetPath2();
Где?

2024-04-20 12:43 UTC, De-Len commented on WindowsFormsApp1/Lab_8-WindowsForms/Model.cs
> +    // "Кичливость философии не совмещается со смирением"
+

2024-04-20 12:43 UTC, De-Len commented on WindowsFormsApp1/Lab_8-WindowsForms/Model.cs
> +        public void SynsDirectory(string Path1, string Path2, DirectoryChoice directoryChoice, out List<string> createdFiles, out List<string> deletedFiles, out List<string> replacedFiles)
+

2024-04-20 12:43 UTC, De-Len commented on WindowsFormsApp1/Lab_8-WindowsForms/IView.cs
> +        string TextBox2Text { get; set; }
+

2024-04-20 12:43 UTC, De-Len commented on WindowsFormsApp1/Lab_8-WindowsForms/Model.cs
> +        static bool FilesAreEqual(string file1, string file2)
+

2024-04-20 12:43 UTC, De-Len commented on WindowsFormsApp1/Lab_8-WindowsForms/Model.cs
> +        public void SynsDirectory(string Path1, string Path2, DirectoryChoice directoryChoice, out List<string> createdFiles, out List<string> deletedFiles, out List<string> replacedFiles)
+

2024-04-20 12:43 UTC, De-Len commented on WindowsFormsApp1/Lab_8-WindowsForms/Model.cs
> +                MessageBox.Show("Директории уже синхронизированы", "Ошибка", MessageBoxButtons.OK, MessageBoxIcon.Information);
+

2024-04-20 12:44 UTC, De-Len commented on WindowsFormsApp1/Lab_8-WindowsForms/Presenter.cs
> +        private void Sync2(object sender, EventArgs e)
Done

2024-04-20 12:44 UTC, De-Len commented on WindowsFormsApp1/Lab_8-WindowsForms/Model.cs
> +                    replacedFiles.Add(fileName);
Done

2024-04-20 12:50 UTC, De-Len commented on WindowsFormsApp1/Lab_8-WindowsForms/View.cs
> +            return _presenter.GetPath1();
Done

2024-04-20 12:53 UTC, De-Len commented on WindowsFormsApp1/Lab_8-WindowsForms/Presenter.cs
> +        public string GetPath1()
Done

2024-04-20 12:56 UTC, De-Len commented on WindowsFormsApp1/Lab_8-WindowsForms/IView.cs
> +        string GetPath2();
Done

2024-04-20 13:02 UTC, De-Len commented on WindowsFormsApp1/Lab_8-WindowsForms/View.cs
> +        private void button2_Click(object sender, EventArgs e)
Done

2024-04-21 12:38 UTC, De-Len commented on WindowsFormsApp1/Lab_8-WindowsForms/View.Designer.cs
> +        public string Label3Text
Отформатировал*

2024-04-21 12:50 UTC, Hamjoshua requested changes

2024-04-21 12:50 UTC, Hamjoshua commented on WindowsFormsApp1/Lab_8-WindowsForms/View.cs
> +            string path2 = _presenter._iView.GetPath2InTextBox2Text;
Объявил, но не используешь: path1 и path2

2024-04-21 12:50 UTC, Hamjoshua commented on WindowsFormsApp1/Lab_8-WindowsForms/View.Designer.cs
> +        public string LogOutputLabel3Text
Освободи дизайнер от человеческого кода! Пусть этот кусок сгенерированного кода зиждет в спокойствии

2024-04-21 12:50 UTC, Hamjoshua commented on WindowsFormsApp1/Lab_8-WindowsForms/Model.cs
> +                DeleteFiles(missingFilesInPath2, Path1, deletedFiles, "DELETED");
Гораздо лучше

2024-04-21 12:50 UTC, Hamjoshua commented on WindowsFormsApp1/Lab_8-WindowsForms/IView.cs
> +        string GetPath2InTextBox2Text { get; set; }
Плеоназмы, глаголы в названии обычных полей, указание на объекты из другого мира... 

> "Все дьяволом продумано хитро"
> "Но беспощадный вирус вырожденья"
> "Сточил бесславно все его нутро"

Пиши проще! Path1 / FirstPath

2024-04-21 12:50 UTC, Hamjoshua commented on WindowsFormsApp1/Lab_8-WindowsForms/View.cs
> +        private void label1_Click(object sender, EventArgs e)
Эту хрень тяжело вывести, за ошибку считать не буду. Но впредь старайся не нажимать два раза на элементы)

2024-04-21 12:51 UTC, De-Len commented on WindowsFormsApp1/Lab_8-WindowsForms/View.cs
> +            string path2 = _presenter._iView.GetPath2InTextBox2Text;
Done

2024-04-21 12:51 UTC, De-Len commented on WindowsFormsApp1/Lab_8-WindowsForms/View.Designer.cs
> +        public string LogOutputLabel3Text
Done

2024-04-21 12:52 UTC, De-Len commented on WindowsFormsApp1/Lab_8-WindowsForms/Model.cs
> +                DeleteFiles(missingFilesInPath2, Path1, deletedFiles, "DELETED");
Done

2024-04-21 13:00 UTC, De-Len commented on WindowsFormsApp1/Lab_8-WindowsForms/IView.cs
> +        string GetPath2InTextBox2Text { get; set; }
Done

_"Я знаю, что придет тоска
И дружбу, и любовь наруша,
Отчаявшись, я чужака -
В самом себе вдруг обнаружу.
Но в поединке между ним
И тем во мне, кто жизнь прославил,
Я буду сам судьей своим.
И будет этот бой неравен"._

2024-04-21 13:04 UTC, De-Len commented on WindowsFormsApp1/Lab_8-WindowsForms/View.cs
> +        private void label1_Click(object sender, EventArgs e)
Понял ваше негодование: атомарность бытия долженствует заставить нас не уподоблять силы на заведомое тленное бдение рекреативного обскурантизма.

2024-04-21 13:16 UTC, Hamjoshua approved these changes

2024-04-21 13:17 UTC, merged